Repository wtg/shuttletracker, pull requests merged in 2018-03, with the labels that each got.

#128 Dark mode persistence with localStorage
  static/js/frontend.js
Labels: enhancement, frontend, ready

#131 Update to new logo
  static/images/wtg.svg
Labels: frontend, ready

#126 Custom Admin Alert Messages
  admin.html
  api/api.go
  api/notifications.go
  database/database.go
  database/mongodb.go
  model/model.go
  static/css/application.css
  static/dist/bulma-0.6.2/package.json
  static/js/admin.js
  static/js/frontend.js
  static/js/messages.js
Labels: enhancement, ready

#135 About modal
  .travis.yml
  api/notifications.go
  api/routes.go
  database/database.go
  static/css/application.css
  static/js/frontend.js
Labels: ready

#123 Set ETag header
  .codecov.yaml
  api/api.go
  api/etag.go
  api/etag_test.go
  api/routes.go
  api/vehicles.go
  vendor/vendor.json
Labels: ready

#141 Fix modal in Firefox
  static/css/application.css
Labels: ready

#136 Route Scheduling Fix
  api/routes.go
  api/routes_test.go
  database/database.go
  database/database_test.go
  database/mongodb.go
  model/model.go
  model/time.go
  model/time_test.go
  static/js/routes.js
Labels: ready

#140 Compress responses
  .travis.yml
  api/api.go
  api/api_test.go
  api/etag_test.go
  database/mock.go
  test.sh
  vendor/vendor.json
Labels: ready

#142 Generate messages client side
  api/api.go
  api/vehicles.go
  api/vehicles_test.go
  static/js/frontend.js
Labels: ready

#144 Fix potential live indicator bug
  static/js/frontend.js
Labels: frontend, ready

#146 Load vehicles as soon as the page is loaded
  static/js/frontend.js
Labels: frontend, ready
